name: Crystal Ameba Linter
description: A GitHub Action that lints Crystal code with Ameba
author: Sijawusz Pur Rahnama <sija@sija.pl>

branding:
  icon: code
  color: red

inputs:
  config:
    description: Path to Ameba configuration file
  version:
    description: Version of Ameba rules to use
  min-severity:
    description: Minimum severity of issues to report
  only:
    description: Run only given rules (or groups)
  except:
    description: Disable the given rules (or groups)
  formatter:
    description: Name of the formatter to use
    default: github-actions

runs:
  using: docker
  image: Dockerfile
  entrypoint: /usr/bin/ameba
  args:
    - "--format"
    - "${{ inputs.formatter }}"
    - "--config"
    - "${{ inputs.config }}"
    - "--up-to-version"
    - "${{ inputs.version }}"
    - "--min-severity"
    - "${{ inputs.min-severity }}"
    - "--only"
    - "${{ inputs.only }}"
    - "--except"
    - "${{ inputs.except }}"
